version: '3'
services:
  foreign_ethmonitor:
    image: darcher/giveth-base:latest
    entrypoint: ["/bin/sh", "start_foreign_ethmonitor.sh"]
    stop_signal: SIGINT
    stdin_open: true
    tty: true
    environment:
      ETHMONITOR_PORT: 8989
      ETHMONITOR_CONTROLLER: ${ETHMONITOR_CONTROLLER:-deploy}
      VERBOSITY: ${VERBOSITY:-4}
      ANALYZER_ADDR: ${ANALYZER_ADDR:-host.docker.internal:1234}

  foreign_doer:
    image: darcher/giveth-base:latest
    entrypoint: ["/bin/sh", "start_foreign_doer.sh"]
    stop_signal: SIGINT
    environment:
      ETHMONITOR_ADDR: foreign_ethmonitor:8989
      VERBOSITY: 3
    ports:
      - "8546:8545"
      - "9546:8546"
      - "30304:30303"
      - "30304:30303/udp"

  foreign_talker:
    image: darcher/giveth-base:latest
    entrypoint: ["/bin/sh", "start_foreign_talker.sh"]
    stop_signal: SIGINT
    network_mode: service:foreign_doer
    environment:
      ETHMONITOR_ADDR: foreign_ethmonitor:8989
      VERBOSITY: 3

  home_ethmonitor:
    image: darcher/giveth-base:latest
    entrypoint: ["/bin/sh", "start_home_ethmonitor.sh"]
    stop_signal: SIGINT
    stdin_open: true
    tty: true
    environment:
      ETHMONITOR_PORT: 8989
      ETHMONITOR_CONTROLLER: ${ETHMONITOR_CONTROLLER:-deploy}
      VERBOSITY: ${VERBOSITY:-4}
      ANALYZER_ADDR: ${ANALYZER_ADDR:-host.docker.internal:1234}

  home_doer:
    image: darcher/giveth-base:latest
    entrypoint: ["/bin/sh", "start_home_doer.sh"]
    stop_signal: SIGINT
    environment:
      ETHMONITOR_ADDR: home_ethmonitor:8989
      VERBOSITY: 3
    ports:
      - "8545:8545"
      - "9545:8546"
      - "30303:30303"
      - "30303:30303/udp"

  home_talker:
    image: darcher/giveth-base:latest
    entrypoint: ["/bin/sh", "start_home_talker.sh"]
    stop_signal: SIGINT
    network_mode: service:home_doer
    environment:
      ETHMONITOR_ADDR: home_ethmonitor:8989
      VERBOSITY: 3
